name: Build/Test/Verify/Release
on: [push]
env:
  ROM_VERSION: v0.4.0
  KERNEL_VERSION: v0.7.0
  ROOTFS_VERSION: v0.6.0
  TEST_VERSION: v0.8.0
  GROUND_TRUTH_VERSION: v0.8.0-0004
  BUILD_CACHE_VERSION: v0.6.0-0001
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libreadline-dev libboost-container-dev libboost-program-options-dev libboost-serialization-dev protobuf-compiler protobuf-compiler-grpc libprotobuf-dev libgrpc++-dev patchelf automake

      - name: Build third-party dependencies
        id: build_dep
        run: make -j$(nproc) dep

      - name: Build
        run: make -j$(nproc)

      - name: Install [/opt/cartesi]
        run: make install

      - name: Fix install permissions [/opt/cartesi]
        run: find /opt/cartesi -type d -exec chmod 755 {} +

      - name: Upload emulator
        uses: actions/upload-artifact@master
        with:
          name: emulator
          path: /opt/cartesi

  test:
    name: Test
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download emulator
        uses: actions/download-artifact@master
        with:
          name: emulator
          path: /opt/cartesi

      - name: Create images folder
        run: mkdir -m 755 -p /opt/cartesi/share/images

      - name: Fix install directories and permissions [/opt/cartesi]
        run: |
          find /opt/cartesi -type d -exec chmod 755 {} +
          find /opt/cartesi -type f -exec chmod 644 {} +
          find /opt/cartesi/bin -type f \! -iname "*.lua" -exec chmod 755 {} +
          find /opt/cartesi/lib -type f -exec chmod 755 {} +

      - name: Install Ubuntu dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libboost-all-dev libboost-program-options1.71.0 libboost-serialization1.71.0 libprotobuf17 libprotobuf-lite17 libgrpc++1 netcat lcov llvm clang

      - name: Download [rootfs.ext2]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cartesi/image-rootfs
          tag: v0.6.0
          file: rootfs.ext2
          token: ${{ secrets.CI_TOKEN }}

      - name: Download [kernel.bin]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cartesi/image-kernel
          tag: v0.7.0
          file: linux-5.5.19-ctsi-2.bin
          token: ${{ secrets.CI_TOKEN }}

      - name: Download [rom.bin]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cartesi/machine-emulator-rom
          tag: v0.4.0
          file: rom.bin
          token: ${{ secrets.CI_TOKEN }}

      - name: Move images to cartesi images folder
        run: |
          mv rom.bin linux-5.5.19-ctsi-2.bin rootfs.ext2 /opt/cartesi/share/images/
          cd /opt/cartesi/share/images/ && ln -s linux-5.5.19-ctsi-2.bin linux.bin

      - name: Download test suite
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cartesi/machine-tests
          tag: v0.8.0
          file: machine-tests-v0.8.0.tar.gz
          token: ${{ secrets.CI_TOKEN }}

      - name: Untar test suite
        run: mkdir -p /opt/cartesi/tests && tar -xzf machine-tests-${TEST_VERSION}.tar.gz -C /opt/cartesi/tests

      - name: Checkout emulator source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Build third-party dependencies
        id: build_dep
        run: make -j$(nproc) dep

      - name: Install third-party dependencies
        id: install_dep
        run: make install-dep

      - name: Calculate coverage
        run: |
          export CARTESI_IMAGES_PATH=/opt/cartesi/share/images
          export CARTESI_TESTS_PATH=/opt/cartesi/tests
          export TEST_PATH=/opt/cartesi/tests
          export PATH=/opt/cartesi/bin:$PATH
          export LD_LIBRARY_PATH=/opt/cartesi/lib
          cd src && make coverage-build-gcc
          cp ./cartesi.so /opt/cartesi/lib/luapp/5.3/cartesi.so
          make coverage-calc-gcc
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
